### Assignment 9 - Numpy - Em Kay

In [1]:
import numpy as np
import pandas as pd

#### 1.	How to concatenate two numpy arrays column-wise and row-wise?

In [2]:
x,y = np.array(([1,2,3],[7,8,9])), np.array(([4,5,6],[10,11,12]))
col_wise = np.concatenate((x,y), axis=0) #axis=0 is column-wise
row_wise = np.concatenate((x,y), axis=1) ##axis=1 is row-wise

In [3]:
display("x", x)
display("y", y)
display("col_wise", col_wise)
display("row_wise", row_wise)

'x'

array([[1, 2, 3],
       [7, 8, 9]])

'y'

array([[ 4,  5,  6],
       [10, 11, 12]])

'col_wise'

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [ 4,  5,  6],
       [10, 11, 12]])

'row_wise'

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

#### 2.	Consider the random number generation functions in NumPy generate a set of random numbers using the function rand.

In [4]:
two={i for i in np.random.rand(1,5)[0]}
display(two)

{0.10750792640667672,
 0.23070921566878166,
 0.24807476000489426,
 0.4469912908718384,
 0.5000645156536581}

#### 3.	Create a 3D array of shape 5x3x2 to contain random decimal numbers between 5 and 10.

In [5]:
three = np.random.uniform(low=5, high=10, size=(5,3,2))
display("three", three)


'three'

array([[[5.54526971, 5.33883659],
        [6.63103452, 8.20266931],
        [8.25020962, 8.81232963]],

       [[9.58403131, 9.23670187],
        [8.43966432, 7.44782152],
        [7.44588549, 5.47631752]],

       [[6.57456884, 7.81912076],
        [8.59651915, 9.88296927],
        [8.48962986, 9.25064417]],

       [[6.07326961, 5.81869665],
        [6.40860536, 9.49262727],
        [5.91051051, 7.9575605 ]],

       [[5.17493336, 6.64242882],
        [9.90836393, 6.62864318],
        [7.10213034, 7.33016326]]])

#### 4.	Create a utility function to generate random arrays using def random_array() takes number of elements as one of the argument, and np.randint()

In [6]:
#help(np.random.randint)
def random_array(no_elements):
    x=np.random.randint(1,10, size=no_elements)
    return(x)

display(random_array(random_array(5)[-1]))

array([3, 2, 6])

####5.	Create and Compute median using both Naive method and Numpy function np.median()

In [7]:
case1=np.array([1,2,3,4,5])
case2=np.array([2,4,6,8])
case3=np.random.uniform(low=5, high=10, size=(5,1))
cases=[case1,case2,case3]

def naive_median(array):
    array = sorted(array)
    #print(array)
    a_len = len(array)
    if a_len % 2 == 1:
        return(array[round(a_len/2)])
    bounds_indxs=(int(a_len/2 -1), int(a_len/2))
    #print(f"bounds_indxs:{bounds_indxs}")
    #print(f"vals:{array[bounds_indxs[0]], array[bounds_indxs[1]]}")
    return(array[bounds_indxs[0]] + array[bounds_indxs[1]])/2
           
for c in cases:
    print(f"case: {c}\nnaive_median(case):{naive_median(c)}\nnp.median(case):{np.median(c)}\n\n")
    assert(naive_median(c) == np.median(c))

case: [1 2 3 4 5]
naive_median(case):3
np.median(case):3.0


case: [2 4 6 8]
naive_median(case):5.0
np.median(case):5.0


case: [[8.6108754 ]
 [6.14175853]
 [6.36007086]
 [7.02804877]
 [5.99837375]]
naive_median(case):[6.36007086]
np.median(case):6.360070864922476




#### 6.	Create naive function to compute variance function using python.

In [8]:
#https://en.wikipedia.org/wiki/Variance#Definition
#https://www.mathsisfun.com/data/standard-deviation.html

def naive_variance(array):
    def mean(a):
        return(np.sum(a)/len(a))
    _m = mean(array)
    n_a = [(i - _m)**2 for i in array]
    _v = mean(n_a)
    return(_v)
    
#naive_variance([5,10,15])
#naive_variance([5,10,15,20])
display("dog height example per mathisfun.com link", naive_variance([600, 470, 170, 430, 300]))

'dog height example per mathisfun.com link'

21704.0

#### 7.	Convert a 1D array to a 2D array with 2 rows.

e.g. 
Input Array: ([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Output: [[0, 1, 2, 3, 4],
 [5, 6, 7, 8, 9]]


In [9]:
a = np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
display(a.reshape(2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### 8.	How to stack two arrays vertically? Stack arrays A and B vertically?

In [10]:
a = np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
b = a+a

display(np.vstack((a,b)))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]])

#### 9.	Create a function using numpy to get the common items between two python numpy arrays?

In [11]:
def my_intersect(a0,b0):
    a_set = set(a0)
    b_set = set(b0)
    c0 = a_set.intersection(b_set)
    c0 = np.array(list(c0))
    return(c0)

display("my_intersect(a,b)", my_intersect(a,b))
display("np.intersect1d(a,b)", np.intersect1d(a,b))

display("my_intersect([1,2,3,4,4],[4,4,1,8,8])", my_intersect([1,2,3,4,4],[4,4,1,8,8]))
display("np.intersect1d([1,2,3,4,4],[4,4,1,8,8])",np.intersect1d([1,2,3,4,4],[4,4,1,8,8]))

'my_intersect(a,b)'

array([0, 2, 4, 6, 8])

'np.intersect1d(a,b)'

array([0, 2, 4, 6, 8])

'my_intersect([1,2,3,4,4],[4,4,1,8,8])'

array([1, 4])

'np.intersect1d([1,2,3,4,4],[4,4,1,8,8])'

array([1, 4])

#### 10.	Create a python function to get the positions where elements of two arrays match using Numpy function?

In [12]:
a,b = np.array([1,2,3,4,4]), np.array([6,2,0,8,4])

def match_indxs(a0,b0):
    assert len(a0) >= len(b0)
    matches=list()
    i=0
    while i < len(a0):
        if a0[i]==b0[i]:
            matches.append(i)
        i+=1
    return(matches)

display("match_indxs(a,b)", match_indxs(a,b))

'match_indxs(a,b)'

[1, 4]

#### 11.	How to create a 2D array containing random floats between 5 and 10?

In [13]:
display(np.random.uniform(low=5, high=10, size=(3,2)))

array([[7.04103693, 6.72563521],
       [7.23630274, 9.25168605],
       [6.22149936, 6.88878093]])

#### 12.	Extract the text column species from the 1D iris imported using following url:
https://raw.githubusercontent.com/ammishra08/MachineLearning/master/Datasets/iris.csv


In [14]:
iris_data = np.genfromtxt(r"https://raw.githubusercontent.com/ammishra08/MachineLearning/master/Datasets/iris.csv", delimiter=',', 
                          dtype=np.dtype('str'), encoding='utf-8', usecols=[-1])

iris_data=np.delete(iris_data, 0, 0)
display(iris_data)

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

#### 13.	How to Convert the 1D iris to 2D array iris_2d by omitting the species column and dropping first row?

In [15]:
iris_data = np.genfromtxt(r"https://raw.githubusercontent.com/ammishra08/MachineLearning/master/Datasets/iris.csv", delimiter=',', 
                          dtype=float, encoding='utf-8', usecols=[0,1,2,3], skip_header=1)
display(iris_data)


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

#### 14.	How to compute the mean, median, standard deviation of a numpy array on the same iris dataset?

In [16]:
#iris_data
#display(iris_data[:, 0])#column
#display(iris_data[0 , :]) #row

def naive_stdv(a):
    return(np.sqrt(naive_variance(a)))

def getcols(a):
    return(len(a[0,:]))

def colwise_funccall(a, func, col):
    return(func(a[:,col]))

s0=''
for col in range(getcols(iris_data)):
    mean=colwise_funccall(iris_data, np.mean, col)
    median=colwise_funccall(iris_data, naive_median, col)
    stdv=colwise_funccall(iris_data, naive_stdv, col)
    s1=f"col:{col},\nmean:{mean},\nmedian:{median},\nstdv:{stdv},\n\n"
    print(s1)
    s0+=s1
    
display(s0)

col:0,
mean:5.843333333333334,
median:5.8,
stdv:0.8253012917851409,


col:1,
mean:3.0573333333333337,
median:3.0,
stdv:0.4344109677354946,


col:2,
mean:3.7580000000000005,
median:4.35,
stdv:1.759404065775303,


col:3,
mean:1.1993333333333336,
median:1.3,
stdv:0.7596926279021594,




'col:0,\nmean:5.843333333333334,\nmedian:5.8,\nstdv:0.8253012917851409,\n\ncol:1,\nmean:3.0573333333333337,\nmedian:3.0,\nstdv:0.4344109677354946,\n\ncol:2,\nmean:3.7580000000000005,\nmedian:4.35,\nstdv:1.759404065775303,\n\ncol:3,\nmean:1.1993333333333336,\nmedian:1.3,\nstdv:0.7596926279021594,\n\n'

#### 15.	How to scale an array so the values range exactly between 0 and 1 using Admission.csv?
https://raw.githubusercontent.com/ammishra08/MachineLearning/master/Datasets/Admission.csv
Change all the values in the range of 0-1.


In [17]:
data_a = np.genfromtxt(r"https://raw.githubusercontent.com/ammishra08/MachineLearning/master/Datasets/Admission.csv", delimiter=',', 
                           encoding='utf-8', skip_header=1)

#data_a = np.array([[.1, 1, 10, 100],
#                  [.5, 5, 50, 500],
#                  [1, 10, 100, 1000],])


for col in range(getcols(data_a)):
    col_max=colwise_funccall(data_a, max, col)
    data_a[:,col] = data_a[:,col]/col_max
       
display(data_a)


array([[0.002     , 0.99117647, 0.98333333, ..., 0.97278226, 1.        ,
        0.94845361],
       [0.004     , 0.95294118, 0.89166667, ..., 0.89415323, 1.        ,
        0.78350515],
       [0.006     , 0.92941176, 0.86666667, ..., 0.80645161, 1.        ,
        0.74226804],
       ...,
       [0.996     , 0.97058824, 1.        , ..., 0.96370968, 1.        ,
        0.95876289],
       [0.998     , 0.91764706, 0.85833333, ..., 0.84979839, 0.        ,
        0.75257732],
       [1.        , 0.96176471, 0.94166667, ..., 0.91129032, 0.        ,
        0.86597938]])

#### 16.	Compute and Find the number and position of missing values in iris data’s sepal length column. (And few missing values).

In [18]:
any_nan_row = lambda a: np.array([~np.any(np.isnan(row)) for row in a])# True for not nan, False for nan

iris_data_16 = np.genfromtxt(r"https://raw.githubusercontent.com/ammishra08/MachineLearning/master/Datasets/iris.csv", delimiter=',',
                             dtype=float, encoding='utf-8', skip_header=1, usecols=[0],)
display(iris_data.shape)

#iris_data_16 = iris_data_16[np.random.randint(len(iris_data_16[:,1]), size=20), np.random.randint(4, size=20)] = np.nan
iris_data_16[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

#iris_data_16 = np.ma.masked_array(iris_data_16, mask=np.isnan(iris_data_16))

#display(dir(iris_data_16.mask))

#i=0
#for row in any_nan_row(iris_data):  
#np.isnan(iris_data)


(150, 4)

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

#### 1) Combine four series to form and create a Dataframe with name series_data. Use the Dataframe and perform following operations.

In [ ]:
base=['a','b','c','d','e']
s1= pd.Series(base)
s2= pd.Series([c*2 for c in base])